Repository aurora-is-near/rainbow-token-connector, pull requests merged in 2022-03, with the labels that each got.

#95 feature/add-sigma-prime-testing
  .github/workflows/sigma-prime.yml
Labels: enhancement, devops, security, testing

#97 ERC20-connector: check the proof acceptance by tx height
  erc20-connector/contracts/Locker.sol
  erc20-connector/dist/ERC20Locker.full.sol
  erc20-connector/dist/Locker.full.sol
  erc20-connector/test/TokenLocker.js
  res/ERC20Locker.full.bin
  res/Locker.full.bin
Labels: bug

#91 Upgrade Solidity to v0.8.11
  .github/workflows/tests.yml
  erc20-connector/.gitignore
  erc20-connector/build.sh
  erc20-connector/contracts/ERC20Locker.sol
  erc20-connector/contracts/Locker.sol
  erc20-connector/contracts/Migrations.sol
  erc20-connector/contracts/test/NearProverMock.sol
  erc20-connector/contracts/test/TToken.sol
  erc20-connector/dist.sh
  erc20-connector/dist/ERC20Locker.full.sol
  erc20-connector/dist/Locker.full.sol
  erc20-connector/dist/Migrations.full.sol
  erc20-connector/dist/NearProverMock.full.sol
  erc20-connector/dist/TToken.full.sol
  erc20-connector/hardhat.config.js
  erc20-connector/package.json
  erc20-connector/truffle-config.js
  erc20-connector/yarn.lock
  metadata-connector/contracts/test/SampleERC20.sol
  res/AdminControlled.full.abi
  res/AdminControlled.full.bin
  res/ERC20Locker.full.abi
  res/ERC20Locker.full.bin
  res/ERC20Locker.json
  res/Locker.full.abi
  res/Locker.full.bin
  res/Locker.json
  res/Migrations.full.abi
  res/Migrations.full.bin
  res/Migrations.json
  res/NearProverMock.full.abi
  res/NearProverMock.full.bin
  res/NearProverMock.json
  res/ProofKeeper.full.abi
  res/ProofKeeper.full.bin
  res/TToken.full.abi
  res/TToken.full.bin
  res/TToken.json
Labels: enhancement, dependencies
