Repository aurora-is-near/rainbow-token-connector, pull requests merged in 2022-08, with the labels that each got.

#131 FT connector: add whitelisting feature
  .github/workflows/tests.yml
  bridge-common/Cargo.lock
  bridge-common/Cargo.toml
  bridge-common/src/lib.rs
  bridge-common/src/prover.rs
  bridge-common/src/result_types.rs
  bridge-token-factory/Cargo.toml
  bridge-token-factory/src/lib.rs
  erc20-bridge-token/contracts/BridgeToken.sol
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/contracts/BridgeTokenProxy.sol
  erc20-bridge-token/contracts/Migrations.sol
  erc20-bridge-token/contracts/ResultsDecoder.sol
  erc20-bridge-token/contracts/TestBridgeToken.sol
  erc20-connector/dist/ERC20Locker.full.sol
  erc20-connector/dist/TToken.full.sol
  res/ERC20Locker.json
  res/TToken.json
  res/bridge_token.wasm
  res/bridge_token_factory.wasm
  res/rainbow_bridge_near_token_locker.wasm
  token-locker/src/lib.rs
  token-locker/src/token_receiver.rs
  token-locker/src/whitelist.rs
Labels: enhancement, rust, solidity

#135 FT connector: bugs fixes. Improve deploy scripts
  bridge-token-factory/Cargo.toml
  bridge-token/Cargo.toml
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/contracts/ProofConsumer.sol
  erc20-bridge-token/hardhat.config.js
  erc20-bridge-token/scripts/deploy-factory.js
  erc20-bridge-token/scripts/deploy-proof-consumer.js
  erc20-bridge-token/utils/deposit-ft.js
  mock-prover/Cargo.toml
  res/rainbow_bridge_near_token_locker.wasm
  rust-toolchain
  token-locker/src/lib.rs
  token-locker/src/token_receiver.rs
  token-locker/src/unlock_event.rs
  token-locker/src/whitelist.rs
Labels: bug, rust

#141 FT connector: fix withdraw and add scripts
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/hardhat.config.js
  erc20-bridge-token/package.json
  erc20-bridge-token/test/BridgeToken.js
  erc20-bridge-token/utils/deposit-ft.js
  erc20-bridge-token/utils/eth-proof.js
  erc20-bridge-token/utils/near-locker.js
  erc20-bridge-token/utils/near-proof.js
  erc20-bridge-token/utils/withdraw-ft.js
  erc20-bridge-token/yarn.lock
  token-locker/src/unlock_event.rs
Labels: bug, enhancement

#142 FT connector: fix update tokens metadata and add scripts
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/hardhat.config.js
  erc20-bridge-token/package.json
  erc20-bridge-token/test/BridgeToken.js
  erc20-bridge-token/utils/deposit-ft.js
  erc20-bridge-token/utils/near-proof.js
  erc20-bridge-token/yarn.lock
  token-locker/src/lib.rs
Labels: enhancement, solidity

#143 FT connector: solc optimization, CI & binary files updates
  .github/workflows/tests.yml
  Makefile
  bridge-token-factory/build.sh
  erc20-bridge-token/build.sh
  erc20-bridge-token/contracts/test/NearProverMock.sol
  erc20-bridge-token/contracts/test/TestBridgeToken.sol
  erc20-bridge-token/dist.sh
  erc20-bridge-token/dist/BridgeToken.full.sol
  erc20-bridge-token/dist/BridgeTokenFactory.full.sol
  erc20-bridge-token/dist/BridgeTokenProxy.full.sol
  erc20-bridge-token/dist/IProofConsumer.full.sol
  erc20-bridge-token/dist/Migrations.full.sol
  erc20-bridge-token/dist/ProofConsumer.full.sol
  erc20-bridge-token/dist/ResultsDecoder.full.sol
  erc20-bridge-token/hardhat.config.js
  erc20-connector/dist/ERC20Locker.full.sol
  erc20-connector/dist/TToken.full.sol
  res/BridgeToken.json
  res/BridgeTokenFactory.json
  res/BridgeTokenProxy.json
  res/IProofConsumer.json
  res/ProofConsumer.json
  res/ResultsDecoder.json
  res/bridge_token.wasm
  res/bridge_token_factory.wasm
  res/rainbow_bridge_near_token_locker.wasm
Labels: devops, dependencies

#145 FT connector: improvements and fixes
  erc20-bridge-token/contracts/BridgeToken.sol
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/contracts/BridgeTokenProxy.sol
  erc20-bridge-token/contracts/IProofConsumer.sol
  erc20-bridge-token/contracts/ProofConsumer.sol
  erc20-bridge-token/contracts/ResultsDecoder.sol
  erc20-bridge-token/contracts/test/NearProverMock.sol
  erc20-bridge-token/contracts/test/TestBridgeToken.sol
  erc20-bridge-token/dist/BridgeToken.full.sol
  erc20-bridge-token/dist/BridgeTokenFactory.full.sol
  erc20-bridge-token/dist/BridgeTokenProxy.full.sol
  erc20-bridge-token/dist/IProofConsumer.full.sol
  erc20-bridge-token/dist/ProofConsumer.full.sol
  erc20-bridge-token/dist/ResultsDecoder.full.sol
  erc20-bridge-token/test/BridgeToken.js
  res/BridgeToken.json
  res/BridgeTokenFactory.json
  res/BridgeTokenProxy.json
  res/ProofConsumer.json
  res/ResultsDecoder.json
Labels: enhancement, testing, solidity

#151 FT connector: improvements, add more tests
  .github/workflows/tests.yml
  Makefile
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/dist/BridgeTokenFactory.full.sol
  erc20-bridge-token/package-lock.json
  erc20-bridge-token/scripts/deploy-token-upgrade.js
  erc20-bridge-token/test/BridgeToken.js
  erc20-bridge-token/test/helpers.js
  res/BridgeTokenFactory.json
  res/rainbow_bridge_near_token_locker.wasm
  token-locker/Cargo.lock
  token-locker/Cargo.toml
  token-locker/src/lib.rs
  token-locker/src/token_receiver.rs
  token-locker/src/unlock_event.rs
  token-locker/src/whitelist.rs
  token-locker/tests/event_serialization.rs
Labels: enhancement, testing

#152 FT connector: improve pausability
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/contracts/SelectivePausableUpgradable.sol
  erc20-bridge-token/dist/BridgeTokenFactory.full.sol
  erc20-bridge-token/hardhat.config.js
  erc20-bridge-token/scripts/deploy-proof-consumer.js
  erc20-bridge-token/scripts/upgrade-factory.js
  erc20-bridge-token/test/BridgeToken.js
  res/BridgeTokenFactory.json
Labels: enhancement

#153 FT connector: API improvements, add more tests
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/dist/BridgeTokenFactory.full.sol
  erc20-bridge-token/dist/SelectivePausableUpgradable.full.sol
  erc20-bridge-token/scripts/deploy-factory.js
  erc20-bridge-token/scripts/deploy-token-upgrade.js
  erc20-bridge-token/scripts/upgrade-factory.js
  erc20-bridge-token/test/BridgeToken.js
  res/BridgeTokenFactory.json
Labels: enhancement, solidity

#156 FT connector: minor improvements
  erc20-bridge-token/hardhat.config.js
  erc20-bridge-token/scripts/deploy-factory.js
Labels: enhancement, javascript

#157 FT connector: add more scripts
  erc20-bridge-token/hardhat.config.js
Labels: testing, javascript

#158 FT connector: bugs fixes, minor improvements, more tests.
  erc20-bridge-token/contracts/BridgeTokenFactory.sol
  erc20-bridge-token/dist/BridgeTokenFactory.full.sol
  erc20-bridge-token/scripts/deploy-factory-impl.js
  erc20-bridge-token/test/BridgeToken.js
  res/BridgeTokenFactory.json
  res/SelectivePausableUpgradable.json
  res/rainbow_bridge_near_token_locker.wasm
  token-locker/src/lib.rs
  token-locker/src/unlock_event.rs
Labels: bug
