Repository aurora-is-near/rainbow-token-connector, pull requests merged in 2022-01, with the labels that each got.

#89 Fix CI
  .github/workflows/tests.yml
  Makefile
  bridge-token-factory/rust-toolchain
  bridge-token/rust-toolchain
  res/bridge_token.wasm
  res/bridge_token_factory.wasm
  rust-toolchain
Labels: devops

#83 Log record proof for filtering easier by proofs.
  bridge-token-factory/src/lib.rs
Labels: enhancement

#88 Metadata connector: fix incorrect log output
  metadata-connector/contracts/ERC20MetadataLogger.sol
Labels: bug
